; autogenerated memory map

; ROM
; MEM slot 1
ROM              = 0x0000
ROM_SIZE         = 0x8000

; RAM
; MEM slot 2
RAM              = 0x8000
RAM_SIZE         = 0x4000

; MOT
; MEM slot 4
MOT              = 0xD002
MOT_SIZE         = 0x0002

; UART
; MEM slot 3
UART             = 0xD008
UART_SIZE        = 0x0002

; EXT_ROM
; MEM slot 5
EXT_ROM          = 0xD00C
EXT_ROM_SIZE     = 0x0001

