; autogenerated memory map

; ROM
; MEM slot 1
ROM              = 0x0000
ROM_SIZE         = 0x4000

; RAM
; MEM slot 2
RAM              = 0x4000
RAM_SIZE         = 0x8000

; EXRAM
; MEM slot 3
EXRAM            = 0xC000
EXRAM_SIZE       = 0x2002

; UART
; MEM slot 5
UART             = 0xE002
UART_SIZE        = 0x0002

; MOT
; MEM slot 6
MOT              = 0xE004
MOT_SIZE         = 0x0002

; RA8876
; MEM slot 8
RA8876           = 0xE006
RA8876_SIZE      = 0x0002

; SDCARD
; MEM slot 4
SDCARD           = 0xE010
SDCARD_SIZE      = 0x0002

; ETH
; MEM slot 7
ETH              = 0xE400
ETH_SIZE         = 0x0400

