; autogenerated memory map

; ROM
ROM              = 0x0000
ROM_SIZE         = 0x8000

; RAM
RAM              = 0x8000
RAM_SIZE         = 0x4000

; MOT
MOT              = 0xD002
MOT_SIZE         = 0x0002

; UART
UART             = 0xD008
UART_SIZE        = 0x0002

; EXT_ROM
EXT_ROM          = 0xD00C
EXT_ROM_SIZE     = 0x0001

